#!/usr/bin/env python3
"""Re-inject the hero map's camera, renderer and coastline into the bundle.

public/hero-globe.html is a single-file bundle produced by an external tool:
a JSON template plus a manifest of gzipped, base64'd assets. We don't have
that tool, so this script edits the bundle in place rather than rebuilding it
from scratch. It replaces the contents of two sentinel-delimited blocks:

    /* ==== hero-globe/camera ... ==== */   camera.js + the baked land.json
    /* ==== hero-globe/dotmap ... ==== */   dotmap.js

Edit camera.js / dotmap.js / land.json, run this, reload the page. Running it
twice with no source changes rewrites the bundle byte-for-byte.

    python3 scripts/hero-globe/build.py

The map draws itself from land.json and makes no network requests, which is
the point: it previously used third-party tiles, and the provider started
watermarking them with "API key required" without any change on our side.
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.join(HERE, '..', '..', 'public', 'hero-globe.html')

BLOCKS = {
    'camera': ('/* ==== hero-globe/camera — generated by scripts/hero-globe/build.py; edit there ==== */',
               '/* ==== end hero-globe/camera ==== */'),
    'dotmap': ('  /* ==== hero-globe/dotmap — generated by scripts/hero-globe/build.py; edit there ==== */',
               '  /* ==== end hero-globe/dotmap ==== */'),
}


def read(name):
    return open(os.path.join(HERE, name), encoding='utf-8').read()


def span(html, tag):
    """Byte span of one __bundler/<tag> script payload."""
    m = re.search(r'<script type="__bundler/%s">(.*?)</script>' % tag, html, re.S)
    if not m:
        sys.exit('bundle has no __bundler/%s block' % tag)
    return m.group(1), m.span(1)


def replace_block(t, key, body):
    """Swap whatever sits between a block's sentinels for `body`."""
    a, b = BLOCKS[key]
    i, j = t.find(a), t.find(b)
    if i < 0 or j < 0:
        sys.exit('bundle is missing the %s sentinels — restore public/hero-globe.html '
                 'from git and try again' % key)
    return t[:i + len(a)] + body + t[j:]


def encode(o):
    """JSON for embedding inside a <script> tag.

    A literal </script> in the payload would close the host tag early; \\/ is
    a legal JSON escape, so the bytes survive but the parser doesn't see it.
    """
    return json.dumps(o, separators=(',', ':')).replace('</', '<\\/')


def main():
    path = os.path.normpath(BUNDLE)
    html = open(path, encoding='utf-8').read()
    raw, (lo, hi) = span(html, 'template')
    t = json.loads(raw)

    land = json.load(open(os.path.join(HERE, 'land.json')))
    t = replace_block(t, 'camera',
                      '\n' + 'const LAND = %s;' % encode(land) + '\n\n' + read('camera.js'))
    t = replace_block(t, 'dotmap', '\n' + read('dotmap.js'))

    before = html
    html = html[:lo] + encode(t) + html[hi:]

    if html == before:
        print('no change (%s)' % path)
        return
    open(path, 'w', encoding='utf-8').write(html)
    print('wrote %s (%.1f KB)' % (path, len(html) / 1024))


if __name__ == '__main__':
    main()
